ALTER TABLE provider_configs ADD COLUMN need_login BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE provider_configs ADD COLUMN enable BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE provider_configs ADD COLUMN lock BOOLEAN NOT NULL DEFAULT 0;
